clc;
clear all;
close all;
x=input('enter the input sequence');
h=input('enter the impulse response');
y=conv(x,h);
disp(y);
subplot(3,1,1);
n1=0:length(x)-1;
stem(n1,x);
title('input sequence');
subplot(3,1,2);
n2=0:length(h)-1;
stem(n2,h);
title('impulse response');
subplot(3,1,3);
n3=0:length(y)-1;
stem(n3,y);
title('output sequence');