clc;
clear all;
close all;
x=input('enter the input sequence');
h=input('enter the impulse response');
nx=input('index vector for the input sequence');
nh=input('index vector for the impulse response');
a=nx(1)+nh(1);
b=nx(length(x))+nh(length(h));
ny=[a:b];
y=conv(x,h);
disp(y);
subplot(3,1,1);
stem(nx,x);
title('input sequence');
subplot(3,1,2);
stem(nh,h);
title('impulse response');
subplot(3,1,3);
stem(ny,y);
title('output sequence');